export const productInfo = {
    id: "P10001",
    productName: "Apple iPhone 16 Pro 256GB",
    sku: "APL-IP16P-256-BLK",
    category: "Smartphones",
    brand: "Apple",
    description:
        "Premium smartphone with A18 Pro chip, 256GB storage, and 48MP camera.",
};

export const inventory = [
    {
        warehouse: "Bangalore Warehouse",
        location: "Bangalore",
        availableStock: 150,
        reservedStock: 20,
        totalStock: 170,
    },
    {
        warehouse: "Delhi Warehouse",
        location: "Delhi",
        availableStock: 90,
        reservedStock: 10,
        totalStock: 100,
    },
    {
        warehouse: "Mumbai Warehouse",
        location: "Mumbai",
        availableStock: 75,
        reservedStock: 15,
        totalStock: 90,
    },
    {
        warehouse: "Bangalore Warehouse",
        location: "Bangalore",
        availableStock: 150,
        reservedStock: 20,
        totalStock: 170,
    },
    {
        warehouse: "Delhi Warehouse",
        location: "Delhi",
        availableStock: 90,
        reservedStock: 10,
        totalStock: 100,
    },
    {
        warehouse: "Mumbai Warehouse",
        location: "Mumbai",
        availableStock: 75,
        reservedStock: 15,
        totalStock: 90,
    },
    {
        warehouse: "Bangalore Warehouse",
        location: "Bangalore",
        availableStock: 150,
        reservedStock: 20,
        totalStock: 170,
    },
    {
        warehouse: "Delhi Warehouse",
        location: "Delhi",
        availableStock: 90,
        reservedStock: 10,
        totalStock: 100,
    },
    {
        warehouse: "Mumbai Warehouse",
        location: "Mumbai",
        availableStock: 75,
        reservedStock: 15,
        totalStock: 90,
    },
    {
        warehouse: "Bangalore Warehouse",
        location: "Bangalore",
        availableStock: 150,
        reservedStock: 20,
        totalStock: 170,
    },
    {
        warehouse: "Delhi Warehouse",
        location: "Delhi",
        availableStock: 90,
        reservedStock: 10,
        totalStock: 100,
    },
    {
        warehouse: "Mumbai Warehouse",
        location: "Mumbai",
        availableStock: 75,
        reservedStock: 15,
        totalStock: 90,
    },
    {
        warehouse: "Bangalore Warehouse",
        location: "Bangalore",
        availableStock: 150,
        reservedStock: 20,
        totalStock: 170,
    },
    {
        warehouse: "Delhi Warehouse",
        location: "Delhi",
        availableStock: 90,
        reservedStock: 10,
        totalStock: 100,
    },
    {
        warehouse: "Mumbai Warehouse",
        location: "Mumbai",
        availableStock: 75,
        reservedStock: 15,
        totalStock: 90,
    },
    {
        warehouse: "Bangalore Warehouse",
        location: "Bangalore",
        availableStock: 150,
        reservedStock: 20,
        totalStock: 170,
    },
    {
        warehouse: "Delhi Warehouse",
        location: "Delhi",
        availableStock: 90,
        reservedStock: 10,
        totalStock: 100,
    },
    {
        warehouse: "Mumbai Warehouse",
        location: "Mumbai",
        availableStock: 75,
        reservedStock: 15,
        totalStock: 90,
    }
];

export const availability = [
    {
        location: "Bangalore",
        available: true,
        remarks: "Ready for dispatch",
    },
    {
        location: "Delhi",
        available: true,
        remarks: "Limited stock",
    },
    {
        location: "Hyderabad",
        available: false,
        remarks: "Out of stock",
    },
    {
        location: "Bangalore",
        available: true,
        remarks: "Ready for dispatch",
    },
    {
        location: "Delhi",
        available: true,
        remarks: "Limited stock",
    },
    {
        location: "Hyderabad",
        available: false,
        remarks: "Out of stock",
    },
    {
        location: "Bangalore",
        available: true,
        remarks: "Ready for dispatch",
    },
    {
        location: "Delhi",
        available: true,
        remarks: "Limited stock",
    },
    {
        location: "Hyderabad",
        available: false,
        remarks: "Out of stock",
    },
    {
        location: "Bangalore",
        available: true,
        remarks: "Ready for dispatch",
    },
    {
        location: "Delhi",
        available: true,
        remarks: "Limited stock",
    },
    {
        location: "Hyderabad",
        available: false,
        remarks: "Out of stock",
    },
];

export const network = [
    {
      id: 1,
      network: "Apple Supply Chain",
      source: "Apple Factory",
      destination: "Bangalore Warehouse",
      dispatchDate: "2026-06-01",
      expectedArrival: "2026-06-03",
      actualArrival: "2026-06-03",
      status: "Delivered",
    },
    {
      id: 2,
      network: "Apple Supply Chain",
      source: "Bangalore Warehouse",
      destination: "Delhi Warehouse",
      dispatchDate: "2026-06-04",
      expectedArrival: "2026-06-06",
      actualArrival: "2026-06-06",
      status: "Delivered",
    },
    {
      id: 3,
      network: "Apple Supply Chain",
      source: "Bangalore Warehouse",
      destination: "Mumbai Warehouse",
      dispatchDate: "2026-07-01",
      expectedArrival: "2026-07-03",
      actualArrival: null,
      status: "In Transit",
    },
    {
      id: 4,
      network: "Apple Supply Chain",
      source: "Mumbai Warehouse",
      destination: "Retail Store - Mumbai",
      dispatchDate: "2026-07-05",
      expectedArrival: "2026-07-06",
      actualArrival: null,
      status: "Scheduled",
    },
    {
      id: 5,
      network: "Samsung Supply Chain",
      source: "Samsung Factory",
      destination: "Chennai Warehouse",
      dispatchDate: "2026-06-10",
      expectedArrival: "2026-06-12",
      actualArrival: "2026-06-12",
      status: "Delivered",
    },
    {
      id: 6,
      network: "Samsung Supply Chain",
      source: "Chennai Warehouse",
      destination: "Hyderabad Warehouse",
      dispatchDate: "2026-06-14",
      expectedArrival: "2026-06-15",
      actualArrival: "2026-06-15",
      status: "Delivered",
    },
    {
      id: 7,
      network: "Samsung Supply Chain",
      source: "Chennai Warehouse",
      destination: "Pune Warehouse",
      dispatchDate: "2026-07-02",
      expectedArrival: "2026-07-03",
      actualArrival: null,
      status: "In Transit",
    },
    {
      id: 8,
      network: "Samsung Supply Chain",
      source: "Pune Warehouse",
      destination: "Retail Store - Pune",
      dispatchDate: "2026-07-08",
      expectedArrival: "2026-07-09",
      actualArrival: null,
      status: "Scheduled",
    },
  ];